# Generated by Django 5.1.4 on 2025-01-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_heading', models.CharField(max_length=100)),
                ('usr_description', models.CharField(max_length=100)),
                ('usr_code_box', models.CharField(max_length=100)),
                ('usr_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
