# Generated by Django 5.1.4 on 2025-01-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usr_code_box',
            field=models.CharField(max_length=1000),
        ),
    ]
